"""
Metafora API Client for uploading, checking, signing, and deleting Journal XML files.

Interacts with the Metafora API to manage XML files generated by the OJS export pipeline.
"""

import argparse
import json
import os
import sys
import time
from datetime import datetime
from pathlib import Path

import requests
from dotenv import load_dotenv

load_dotenv(dotenv_path=Path(__file__).parent.parent / '.env')

API_KEY = os.getenv('METAFORA_API_KEY')
API_BASE = os.getenv('METAFORA_API_BASE', 'https://metafora.rcsi.science/api/v2')

HEADERS = {'Api-Key': API_KEY}

LOG_PATH = Path(__file__).parent.parent / 'output' / 'upload_log.json'


def load_log(log_path):
    if log_path.exists():
        with open(log_path, 'r') as f:
            return json.load(f)
    return {}


def save_log(log_path, log_data):
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with open(log_path, 'w') as f:
        json.dump(log_data, f, indent=2)


def resolve_file_uid(file_or_uid, log_data, verbose=False):
    if os.path.isfile(file_or_uid):
        entry = log_data.get(file_or_uid)
        if entry and 'file_uid' in entry:
            return entry['file_uid'], file_or_uid
        print(f"ERROR: No upload log entry found for {file_or_uid}")
        sys.exit(1)
    return file_or_uid, None


def poll_status(file_uid, max_wait=120, verbose=False, log_path=None, log_data=None, file_path=None):
    interval = 3
    elapsed = 0
    while elapsed < max_wait:
        t0 = time.time()
        if verbose:
            url = f"{API_BASE}/files/status/?file_uid={file_uid}"
            print(f"-> GET {url}")
        resp = requests.get(
            f"{API_BASE}/files/status/",
            params={'file_uid': file_uid},
            headers=HEADERS,
            timeout=30
        )
        if verbose:
            print(f"<- {resp.status_code} {resp.reason}")
        if resp.status_code != 200:
            print(f"  ERROR: HTTP {resp.status_code} {resp.reason}")
            print(f"  {resp.text}")
            return []
        data = resp.json().get('data', {})
        status_code = data.get('xml', {}).get('status', {}).get('code')
        status_text = data.get('xml', {}).get('status', {}).get('status_text', 'Unknown')
        print(f"  status: {status_text} ({elapsed}s elapsed)")
        if status_code == 3:
            article_uids = [str(a) for a in (data.get('articles') or [])]
            if log_path is not None and log_data is not None and file_path is not None:
                entry = log_data.get(file_path, {})
                entry['file_uid'] = file_uid
                entry['status_code'] = status_code
                entry['status_text'] = status_text
                entry['article_uids'] = article_uids
                log_data[file_path] = entry
                save_log(log_path, log_data)
            print(f"  Processed OK: {len(article_uids)} articles found")
            for uid in article_uids:
                print(f"    {uid}")
            return article_uids
        if status_code == 4:
            print("  ERROR: processing failed")
            if log_path is not None and log_data is not None and file_path is not None:
                entry = log_data.get(file_path, {})
                entry['file_uid'] = file_uid
                entry['status_code'] = status_code
                entry['status_text'] = status_text
                log_data[file_path] = entry
                save_log(log_path, log_data)
            return []
        time.sleep(interval)
        elapsed = int(time.time() - t0) + elapsed
    print(f"  TIMEOUT after {max_wait}s — check later with: status {file_uid}")
    return []


def cmd_upload(args):
    file_path = args.FILE
    if not os.path.isfile(file_path):
        print(f"ERROR: File not found: {file_path}")
        sys.exit(1)

    log_data = load_log(LOG_PATH)

    entry = log_data.get(file_path)
    if entry and entry.get('status_code') == 3:
        print(f"WARNING: {file_path} is already uploaded and processed (status=3).")
        resp = input("Re-upload? [y/N]: ")
        if resp.lower() != 'y':
            print("Skipped.")
            return

    if verbose:
        print(f"-> POST {API_BASE}/files/journal/")
    with open(file_path, 'rb') as f:
        resp = requests.post(
            f"{API_BASE}/files/journal/",
            files={'xml': f},
            headers=HEADERS,
            timeout=30
        )
    if verbose:
        print(f"<- {resp.status_code} {resp.reason}")

    if resp.status_code == 403:
        print("Access denied — check METAFORA_API_KEY in .venv")
        sys.exit(1)
    if resp.status_code == 422:
        body = resp.json()
        message = body.get('message', '')
        desc = body.get('description', '')
        errors = body.get('errors')
        print(f"Validation error (422):")
        if message:
            print(f"  message: {message}")
        if desc:
            for line in desc.strip().splitlines():
                print(f"  {line.strip()}")
        if errors is not None:
            if isinstance(errors, dict):
                for field, msgs in errors.items():
                    print(f"  {field}: {', '.join(msgs) if isinstance(msgs, list) else msgs}")
            elif isinstance(errors, list):
                for err in errors:
                    print(f"  {err}")
            else:
                print(f"  errors: {errors}")
        if getattr(args, 'verbose', False):
            print(f"  raw: {body}")
        sys.exit(1)
    if resp.status_code not in (200, 201):
        print(f"ERROR: HTTP {resp.status_code} {resp.reason}")
        print(resp.text)
        sys.exit(1)

    result = resp.json()
    file_uid = result.get('data', {}).get('file_uid')
    if not file_uid:
        print(f"ERROR: No file_uid in response: {result}")
        sys.exit(1)

    log_data[file_path] = {
        'file_uid': file_uid,
        'uploaded_at': datetime.now().isoformat(),
        'status_code': 1,
        'status_text': 'Uploaded'
    }
    save_log(LOG_PATH, log_data)
    print(f"Uploaded: {file_path} -> file_uid={file_uid}")

    if not args.no_wait:
        article_uids = poll_status(
            file_uid, verbose=args.verbose,
            log_path=LOG_PATH, log_data=log_data, file_path=file_path
        )
        if args.sign and article_uids:
            sign_all(file_uid, article_uids, verbose=args.verbose)


def cmd_status(args):
    log_data = load_log(LOG_PATH)
    file_uid, file_path = resolve_file_uid(args.FILE_OR_UID, log_data, verbose=args.verbose)

    if args.verbose:
        print(f"-> GET {API_BASE}/files/status/?file_uid={file_uid}")
    resp = requests.get(
        f"{API_BASE}/files/status/",
        params={'file_uid': file_uid},
        headers=HEADERS,
        timeout=30
    )
    if args.verbose:
        print(f"<- {resp.status_code} {resp.reason}")

    if resp.status_code == 403:
        print("Access denied — check METAFORA_API_KEY in .venv")
        sys.exit(1)
    if resp.status_code != 200:
        print(f"ERROR: HTTP {resp.status_code} {resp.reason}")
        print(resp.text)
        sys.exit(1)

    data = resp.json().get('data', {})
    xml_status = data.get('xml', {}).get('status', {})
    pdf_status = data.get('pdf', {}).get('status', {})
    articles = [str(a) for a in (data.get('articles') or [])]
    print(f"file_uid: {data.get('file_uid')}")
    print(f"status_code : {xml_status.get('code')}")
    print(f"status_text : {xml_status.get('status_text')}")
    print(f"pdf_uploaded: {pdf_status.get('uploaded', False)}")
    print(f"articles    : {len(articles)}")
    for uid in articles:
        print(f"  {uid}")

    if file_path and file_path in log_data:
        log_data[file_path]['status_code'] = xml_status.get('code')
        log_data[file_path]['status_text'] = xml_status.get('status_text')
        log_data[file_path]['article_uids'] = articles
        save_log(LOG_PATH, log_data)


def sign_all(file_uid, article_uids, verbose=False):
    signed_count = 0
    total = len(article_uids)
    for article_uid in article_uids:
        if verbose:
            print(f"-> PUT {API_BASE}/publications/{article_uid}/sign/")
        resp = requests.put(
            f"{API_BASE}/publications/{article_uid}/sign/",
            headers=HEADERS,
            timeout=30
        )
        if verbose:
            print(f"<- {resp.status_code} {resp.reason}")
        if resp.status_code == 200:
            print(f"  Signed: {article_uid}")
            signed_count += 1
        elif resp.status_code == 409:
            print(f"  Already signed: {article_uid}")
            signed_count += 1
        else:
            body = resp.text
            try:
                body = json.dumps(resp.json())
            except Exception:
                pass
            print(f"  ERROR: {resp.status_code} {body}")
    print(f"Signed {signed_count}/{total} articles")
    return signed_count


def cmd_sign(args):
    log_data = load_log(LOG_PATH)
    file_uid, file_path = resolve_file_uid(args.FILE_OR_UID, log_data, verbose=args.verbose)

    article_uids = []
    if file_path and file_path in log_data:
        article_uids = log_data[file_path].get('article_uids', [])
    if not article_uids:
        if args.verbose:
            print(f"-> GET {API_BASE}/files/status/?file_uid={file_uid}")
        resp = requests.get(
            f"{API_BASE}/files/status/",
            params={'file_uid': file_uid},
            headers=HEADERS,
            timeout=30
        )
        if args.verbose:
            print(f"<- {resp.status_code} {resp.reason}")
        if resp.status_code == 200:
            data = resp.json().get('data', {})
            article_uids = [str(a) for a in (data.get('articles') or [])]
            if file_path:
                log_data[file_path]['article_uids'] = article_uids
                save_log(LOG_PATH, log_data)
    if not article_uids:
        print("ERROR: No article UIDs found. Ensure the file is processed first.")
        sys.exit(1)

    sign_all(file_uid, article_uids, verbose=args.verbose)


def cmd_delete(args):
    log_data = load_log(LOG_PATH)
    file_uid, file_path = resolve_file_uid(args.FILE_OR_UID, log_data, verbose=args.verbose)

    if args.verbose:
        print(f"-> DELETE {API_BASE}/files/{file_uid}")
    resp = requests.delete(
        f"{API_BASE}/files/{file_uid}",
        headers=HEADERS,
        timeout=30
    )
    if args.verbose:
        print(f"<- {resp.status_code} {resp.reason}")

    if resp.status_code == 204:
        print(f"Deleted: {file_uid}")
        if file_path and file_path in log_data:
            del log_data[file_path]
            save_log(LOG_PATH, log_data)
    elif resp.status_code == 409:
        print("Cannot delete: file has signed publications")
        print(resp.text)
    elif resp.status_code == 422:
        print("Cannot delete: file not processed yet")
        print(resp.text)
    else:
        print(f"ERROR: HTTP {resp.status_code} {resp.reason}")
        print(resp.text)


def cmd_check_doi(args):
    doi = args.DOI
    if args.verbose:
        print(f"-> GET {API_BASE}/publications/doi/{doi}")
    resp = requests.get(
        f"{API_BASE}/publications/doi/{doi}",
        params={'public': 'true'},
        headers=HEADERS,
        timeout=30
    )
    if args.verbose:
        print(f"<- {resp.status_code} {resp.reason}")

    if resp.status_code == 403:
        print("Access denied — check METAFORA_API_KEY in .venv")
        sys.exit(1)
    if resp.status_code == 404:
        print(f"DOI not found: {doi}")
        return
    if resp.status_code != 200:
        print(f"ERROR: HTTP {resp.status_code} {resp.reason}")
        print(resp.text)
        sys.exit(1)

    data = resp.json().get('data', {})
    print(f"Found: {doi}")
    print(f"  article_uid: {data.get('article_uid')}")
    print(f"  signed_at: {data.get('signed_at')}")
    print(f"  created_at: {data.get('created_at')}")


def cmd_upload_all(args):
    year_or_dir = args.YEAR_OR_DIR
    journal = args.journal
    sign = args.sign
    dry_run = args.dry_run

    if os.path.isdir(year_or_dir):
        base_dir = Path(year_or_dir)
    else:
        # year_or_dir is a year string like "2025"
        base_dir = Path(__file__).parent.parent / 'output' / year_or_dir

    if not base_dir.is_dir():
        print(f"ERROR: Directory not found: {base_dir}")
        sys.exit(1)

    if journal:
        pattern = f"{journal}_n*.xml"
    else:
        pattern = "*.xml"

    files = sorted(base_dir.glob(pattern))
    if not files:
        print(f"No XML files matching '{pattern}' in {base_dir}")
        sys.exit(0)

    if dry_run:
        print(f"Would upload {len(files)} file(s):")
        for f in files:
            print(f"  {f}")
        return

    log_data = load_log(LOG_PATH)
    total = len(files)
    success = 0
    total_articles = 0

    for fpath in files:
        fpath_str = str(fpath)
        entry = log_data.get(fpath_str)
        if entry and entry.get('status_code') == 3:
            print(f"SKIP (already processed): {fpath_str}")
            success += 1
            total_articles += len(entry.get('article_uids', []))
            continue

        print(f"\n--- Uploading: {fpath_str} ---")
        if args.verbose:
            print(f"-> POST {API_BASE}/files/journal/")
        with open(fpath_str, 'rb') as f:
            resp = requests.post(
                f"{API_BASE}/files/journal/",
                files={'xml': f},
                headers=HEADERS,
                timeout=30
            )
        if args.verbose:
            print(f"<- {resp.status_code} {resp.reason}")

        if resp.status_code == 403:
            print("Access denied — check METAFORA_API_KEY in .venv")
            continue
        if resp.status_code == 422:
            body = resp.json()
            message = body.get('message', '')
            desc = body.get('description', '')
            errors = body.get('errors')
            print(f"Validation error (422):")
            if message:
                print(f"  message: {message}")
            if desc:
                for line in desc.strip().splitlines():
                    print(f"  {line.strip()}")
            if errors is not None:
                if isinstance(errors, dict):
                    for field, msgs in errors.items():
                        print(f"  {field}: {', '.join(msgs) if isinstance(msgs, list) else msgs}")
                elif isinstance(errors, list):
                    for err in errors:
                        print(f"  {err}")
                else:
                    print(f"  errors: {errors}")
            if getattr(args, 'verbose', False):
                print(f"  raw: {body}")
            continue
        if resp.status_code not in (200, 201):
            print(f"ERROR: HTTP {resp.status_code} {resp.reason}")
            print(resp.text)
            continue

        result = resp.json()
        file_uid = result.get('data', {}).get('file_uid')
        if not file_uid:
            print(f"ERROR: No file_uid in response")
            continue

        log_data[fpath_str] = {
            'file_uid': file_uid,
            'uploaded_at': datetime.now().isoformat(),
            'status_code': 1,
            'status_text': 'Uploaded'
        }
        save_log(LOG_PATH, log_data)
        print(f"Uploaded: {fpath_str} -> file_uid={file_uid}")

        article_uids = poll_status(
            file_uid, verbose=args.verbose,
            log_path=LOG_PATH, log_data=log_data, file_path=fpath_str
        )

        if article_uids:
            success += 1
            total_articles += len(article_uids)
            if sign:
                sign_all(file_uid, article_uids, verbose=args.verbose)
        else:
            print(f"  FAILED: {fpath_str}")

    print(f"\nUpload-all complete: {success}/{total} files, {total_articles} articles")


def main():
    parser = argparse.ArgumentParser(description='Metafora API Client')
    subparsers = parser.add_subparsers(dest='command', required=True)

    p_upload = subparsers.add_parser('upload', help='Upload a Journal XML file')
    p_upload.add_argument('FILE', help='Path to XML file')
    p_upload.add_argument('--sign', action='store_true', help='Sign all articles after processing')
    p_upload.add_argument('--no-wait', action='store_true', help='Do not poll for processing status')
    p_upload.add_argument('--verbose', action='store_true', help='Print raw HTTP requests/responses')

    p_status = subparsers.add_parser('status', help='Check status of an uploaded file')
    p_status.add_argument('FILE_OR_UID', help='Path to XML file or raw file_uid')
    p_status.add_argument('--verbose', action='store_true', help='Print raw HTTP requests/responses')

    p_sign = subparsers.add_parser('sign', help='Sign all articles from a processed file')
    p_sign.add_argument('FILE_OR_UID', help='Path to XML file or raw file_uid')
    p_sign.add_argument('--verbose', action='store_true', help='Print raw HTTP requests/responses')

    p_delete = subparsers.add_parser('delete', help='Delete an uploaded file')
    p_delete.add_argument('FILE_OR_UID', help='Path to XML file or raw file_uid')
    p_delete.add_argument('--verbose', action='store_true', help='Print raw HTTP requests/responses')

    p_check_doi = subparsers.add_parser('check-doi', help='Check if a DOI is registered')
    p_check_doi.add_argument('DOI', help='DOI to check')
    p_check_doi.add_argument('--verbose', action='store_true', help='Print raw HTTP requests/responses')

    p_upload_all = subparsers.add_parser('upload-all', help='Upload all XML files for a journal series')
    p_upload_all.add_argument('YEAR_OR_DIR', help='Year (e.g. 2025) or directory path')
    p_upload_all.add_argument('--journal', help='Journal series name prefix (e.g. mathem)')
    p_upload_all.add_argument('--sign', action='store_true', help='Sign all articles after processing')
    p_upload_all.add_argument('--dry-run', action='store_true', help='List files without uploading')
    p_upload_all.add_argument('--verbose', action='store_true', help='Print raw HTTP requests/responses')

    args = parser.parse_args()
    global verbose
    verbose = getattr(args, 'verbose', False)

    if not API_KEY:
        print("ERROR: METAFORA_API_KEY not set. Check your .venv file.")
        sys.exit(1)

    commands = {
        'upload': cmd_upload,
        'status': cmd_status,
        'sign': cmd_sign,
        'delete': cmd_delete,
        'check-doi': cmd_check_doi,
        'upload-all': cmd_upload_all,
    }
    commands[args.command](args)


if __name__ == '__main__':
    main()
